name: Build and Deploy to Sandbox

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Print effective-settings (optional)
        run: mvn help:effective-settings

      - name: Build with Maven
        run: mvn -B package -s .maven/settings.xml

      - name: Stamp artifact file name with commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
          mv $artifactName1 $artifactName2

      - name: Upload artifact 
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: target/*.jar

  upload:
    needs: build
    runs-on: ubuntu-latest
    env:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: List downloaded files
        run: |
          echo "Listing downloaded files:"
          ls -l
          ls target/

      - name: Upload to Exchange
        run: |
          artifactName=$(ls target/*.jar | head -1)
          if [ -z "$artifactName" ]; then
            echo "Error: No artifact found to upload."
            exit 1
          fi
          echo "Uploading $artifactName to MuleSoft Exchange..."
          mvn deploy \
            -s .maven/settings.xml \
            -Dmule.artifact=$artifactName

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    env:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: List downloaded files
        run: |
          echo "Listing downloaded files:"
          ls -l
          ls target/

      - name: Deploy to Sandbox
        run: |
          artifactName=$(ls target/*.jar | head -1)
          if [ -z "$artifactName" ]; then
            echo "Error: No artifact found to deploy."
            exit 1
          fi
          echo "Deploying $artifactName to Sandbox..."
          mvn deploy -DmuleDeploy \
            -Dmule.artifact=$artifactName \
            -s .maven/settings.xml \
            -DskipTests \
            -DskipDeploymentVerification="true"
