name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ main ]
    
jobs:         
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8

      - name: Increment version and commit
        run: |
          # Increment last number in version in pom.xml
          current_version=$(grep "<version>" pom.xml | head -n 1 | awk -F'[><]' '{print $3}')
          incremented_version=$(echo $current_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          sed -i "s/<version>$current_version<\/version>/<version>$incremented_version<\/version>/" pom.xml
                
      - name: Publish to Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" -Dusername="${{ secrets.USERNAME }}" -Dpassword="${{ secrets.PASSWORD }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Deploy to CloudHub 2.0
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" -Ddecryption.key="${{ secrets.DECRYPTION_KEY }}" -Dusername="${{ secrets.USERNAME }}" -Dpassword="${{ secrets.PASSWORD }}" -Danypoint.platform.client_id="${{ secrets.anypoint.platform.client_id }}" -Danypoint.platform.client_secret="${{ secrets.anypoint.platform.client_secret }}"
          #mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" -Ddecryption.key="${{ secrets.DECRYPTION_KEY }}" -Dusername="${{ secrets.USERNAME }}" -Dpassword="${{ secrets.PASSWORD }}"
          #-Ddecryption.key="${{ secrets.DECRYPTION_KEY }}" 
          # -Dusername="${{ secrets.USERNAME }}" -Dpassword="${{ secrets.PASSWORD }}"
